ikalnytskyi/action-setup-postgres

.github/workflows/ci.yml, action.yml
* `inputs.port.default` is converted into string type explicitly since
it must be a string (according to the docs) and because the linter
complained.
* Remove `PGPORT` environment variable from CI since it seems unneeded.
=> Some clean-up

README.md, action.yml, test_action.py
If not explicitly specified, PostgreSQL infers both locale and encoding
from the locale settings upon database initialization. Speaking about
GitHub runners, they all have different locale settings. For instance,
Windows runner uses `CP1252` encoding which renders the database unable
to deal with non-latin characters.
This patch enforces encoding="UTF-8" and locale="en_US.UTF-8" on all
supported platforms in order to ensure that the database behaves the
same way in certain edge cases.
=> Use encoding="UTF-8" and locale="en_US.UTF-8"

action.yml
The `::set-output` command has been deprecated and is scheduled for removal on Jun 1, 2023 [1]. The recommended way to set output parameters today is by writing them to `$GITHUB_OUTPUT` file [2].
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ [2] https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
Resolves: #6
=> Use `$GITHUB_OUTPUT` instead of `::set-output`

.github/workflows/ci.yml, README.md, action.yml, test_action.py
The 'setup-postgres' action used to create a superuser that hasn't been
exposed to users via 'connection-uri' output. The superuser has been
named after GitHub Action's system user (i.e. 'runner'), had no password
and could have been used via PostgreSQL client applications [1] or when
using manually constructed connection URI with no user set.
The user set via action's input parameters used to be unprivileged with
escalated permissions to create databases on-demand. I don't remember
why I made things this way, maybe I got confused somewhere along the
way, but I don't think having both private superuser and public
unprivileged user is a good idea. It's quite common in tests to
dynamically create databases and/or users for applications under test,
thus superuser permissions are required. …
=> BREAKING CHANGE: create superuser

action.yml, test_action.py
It turns out that PostgreSQL comes with weird default that allows passwordless authentication for localhost connections [1]. This essentially means that 'password' input parameter for this action was ignored.
The 'setup-postgres' action's primary use case is to be used on CI where most of the time authentication is desired in order to verify that passwords are passed correctly from applications under test.
This patch enforces password authentication even for localhost connections, making sure that passwords are verified and not ignored. This will break everyone who previously passed wrong password or didn't pass it at all.
[1] https://www.postgresql.org/docs/15/auth-trust.html
Resolves #5
=> BREAKING CHANGE: enforce password authentication

.github/workflows/ci.yml, README.md, action.yml, test_action.py
The 'setup-postgres' action used to set libpq environment variables [1] with connection parameters so the PostgreSQL client applications [2], such as 'psql' or 'createuser', won't require any configuration before using.
Unfortunately these libpq environment variables are also used by all libpq clients including database drivers such as 'psycopg'. While this may sound good, it may as well lead to undesired behaviour and unobvious issues when connection parameters are automatically pulled from environment but most not.
Nevertheless, the need to easy usage of the client applications [2] is indisputable because providing a bunch of connection parameters all the time is tedious. Therefore this patch pushes requires connection parameters to the connection service file [3], so the client …
=> BREAKING CHANGE: don't set connection env vars

.github/workflows/ci.yml
The checkout v2, the version currently in use on CI, depends on node12 which is going to be removed soon. Let's use the latest version in order to get rid of deprecation warnings in logs and remain compatible with GitHun runners.
=> CI: Bump actions/checkout to v4

.github/workflows/ci.yml, action.yml
The macOS 13 runner image isn't shipped with pre-installed PostgreSQL server. Even though it has Beta status, it'd be nice to support this runner image too.
=> Add macOS 13 support

README.md, action.yml, test_action.py
Unfortunately, the Windows runner has some PostgreSQL environment
variables set, which are neither set for Linux or macOS runners. This is
may be especially confusing since variables such as PGUSER or PGPASSWORD
may point to a user that doesn't exist.
Since one of the design decisions made previously is to restrain this
action from pointing to any user by default, we better unset these
environment variables to avoid confusion.
In addition to that change, let's also mention in the README file that
it's up to users to set connection parameters whatever way they prefer.
Reported-by: @bkoelman
Fixes: #17
=> Unset PG* env vars except PGSERVICEFILE

action.yml
Due to some dark magic used to prepare the macOS 13 runner, the brew install command fails to link unrelated kegs, such as `python@3.12`. Fortunately, since `python@3.12` is a dependency of a dependency, and that dependency is already installed, we can workaround the issue by forcing Homebrew to do not try upgrading dependencies unless absolutely neccessary.
Fixes: #27
=> Fix macOS 13 support

.github/workflows/ci.yml, action.yml
The macOS 14 runner image isn't shipped with pre-installed PostgreSQL server. Even though it has Beta status, it'd be nice to support this runner image too.
=> Add macOS 14 support

.github/workflows/ci.yml, action.yml, test_action.py
Turns out that Windows Server 2019 does not support locale names specified in the format defined by the POSIX standard. This patch converts the POSIX format to the one supported by Windows 2019.
In addition to that, this patch adds all supported action runners to the continue integration, so we can make sure that this action works properly on every supported platform.
Reported-by: Irena Rindos
Fixes: #25
=> Add support for missing action runners

test_action.py
In PostgreSQL 16, both `LC_COLLATE` and `LC_CTYPE` server variables have been removed. This patch rewrites one test that checks their values in order to make tests compatible with PostgreSQL 16, which is shipped with Ubuntu 24.04 runners.
Reported-by: Yuri Astrakhan
Resolves: #38
=> Test database locale, not server variables

.github/workflows/ci.yml
Ensure this action would pass on all available GitHub runners
=> Add more CI test platforms

.github/workflows/ci.yml, README.md, action.yml, test_action.py
One of the foundational principles of this action was to use GitHub
runners preinstalled PostgreSQL binaries. The rationale was simple:
* Make sure the action is fast and no installation is required.
* Make sure it's safe and doesn't reach out to external servers.
* Make sure the action is easy to audit.
Unfortunately, those foundational principles aren't working well
anymore due to the following reasons:
* Ubuntu 24.04 is shipped with PostgreSQL 16, while other runners ship
PostgreSQL 14. It's not nice when different versions are used on
different runners.
* macOS 13 & 14 runners are no longer shipped with preinstalled
PostgreSQL, which means we have to install the server.
* Many FOSS users are attracted by using the most recent PostgreSQL,
and not stuck with few years old release.
This …
=> Add 'postgres-version' input parameter

.github/workflows/ci.yml, README.md, action.yml, test_action.py
There are two cases when PostgreSQL with SSL enabled may come handy. The first one is when PostgreSQL driver developers want to test SSL support in their drivers. The second one is when you come to depend on some self-signed certificates and you want to test your application end-to-end, i.e. with certificates being used.
=> Add SSL support

README.md
Originally the v16 default was added in this commit:
- https://github.com/ikalnytskyi/action-setup-postgres/commit/b5b4c349fc726b8eba33c19f7f6e4df3156f01da
Most of the commit is about v16 as a default, and then parts of the commit only add v15.
I'm assuming that it was intended for v16 to be the default, since the `action.yml` has `16` as the default:
https://github.com/ikalnytskyi/action-setup-postgres/blob/079b07305688c24b4e4c96ec686bd542ede25e05/action.yml#L24-L26
=> Change readme to mention v16 default

action.yml
When `brew` is used by this action, it generates a bunch of warnings which are picked up by the github actions capture system and are shown to end users. They are noisy and most of them are expected. In order to avoid alerting end users, this patch suppresses them by passing 'quiet' parameter to the `brew` binary, unlinking linked keg and suppressing env hints.
=> Suppress Homebrew warnings

.github/workflows/ci.yml
The macOS 12 actions runner has been deprecated on 2024-10-07 and is planned for complete removal on 2024-12-03 [^1]. I believe it's about time to stop using macOS 12, and instead cover macOS 15 (beta) instead.
[^1]: https://github.com/actions/runner-images/issues/10721
=> Drop macOS 12 support, add macOS 15 instead

.github/workflows/ci.yml, action.yml, tests/test_action.py
Both Ubuntu 20.04 and Windows 2019 runners have been retired and are no longer available.
=> Remove retired runners from CI
